/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controller.ControllerDocgia;
import Controller.ControllerPhieumuon;
import Controller.ControllerSach;
import Controller.ControllerChitietphieumuon;
import Dao.Connect;

import Model.ChitietPhieuMuon;

import Model.Phieumuon;
import Model.Sach;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;

import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import javax.swing.table.TableRowSorter;

/**
 *
 * @author UKiel
 */
public class GUI_DocGia extends javax.swing.JFrame {

    public ControllerSach CtrSach = new ControllerSach();
    public ControllerPhieumuon CtrPM = new ControllerPhieumuon();
    public ControllerDocgia CtrDG = new ControllerDocgia();
    public ControllerChitietphieumuon CtrCTPM = new ControllerChitietphieumuon();

    Boolean checkLoading = false;

    //
    String MaTaikhoan;
    String maDocgia;

    int dangmuon;
    int max;

    //
    /**
     * Creates new form GUI_DocGia
     */
    
    public GUI_DocGia(String maTaikhoan, int soluongmuon) {
        initComponents();

        MaTaikhoan = maTaikhoan;
        maDocgia = CtrDG.CtrgetDGbymaTaikhoan(MaTaikhoan).getMaDocgia();
        max = 3 - soluongmuon;

        loadmaDanhMuc();
        loadmaTheLoai();

        filldataTableSach();
        setHeaderTbl(TableSach);

        setluotmuonconlai();
        setHeaderTbl(TableDSmuon);

        setHeaderTbl(TableDangmuon);
        filldatatableDSmuon(maDocgia);
        

        checkLoading = true;
    }

    public void setluotmuonconlai() {
        lbluotmuon1.setText(String.valueOf(max));
    }

    public void setSoluongmuon() {
        dangmuon = TableDSmuon.getRowCount();
        lbluotmuon.setText(String.valueOf(dangmuon));
        if (max >= dangmuon) {
            lbluotmuon.setForeground(Color.black);
        } else {
            lbluotmuon.setForeground(Color.red);
        }
    }

    public void setHeaderTbl(javax.swing.JTable tbl) {
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) tbl.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(0);
        tbl.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 18));
        tbl.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ooo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSach = new javax.swing.JTable();
        btnThongtinSach = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfTenSach = new javax.swing.JTextField();
        cbtheloai = new javax.swing.JComboBox<>();
        cbDanhmuc = new javax.swing.JComboBox<>();
        btnLammoi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableDSmuon = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbluotmuon = new javax.swing.JLabel();
        lbluotmuon1 = new javax.swing.JLabel();
        btnxoa = new javax.swing.JButton();
        btnguiphieumuon = new javax.swing.JButton();
        cbThoigianmuon = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbluotmuon2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableDangmuon = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ooo.setBackground(new java.awt.Color(90, 185, 234));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/login.png"))); // NOI18N
        jButton1.setText("Đăng suất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/VKU.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("QUẢN LÝ THƯ VIỆN");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("ĐẠI HỌC CÔNG NGHỆ THÔNG TIN VÀ TRUYỀN THÔNG VIỆT HÀN");

        javax.swing.GroupLayout oooLayout = new javax.swing.GroupLayout(ooo);
        ooo.setLayout(oooLayout);
        oooLayout.setHorizontalGroup(
            oooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oooLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(oooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oooLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(oooLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(259, 259, 259)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        oooLayout.setVerticalGroup(
            oooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oooLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oooLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.setBackground(new java.awt.Color(193, 200, 228));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 102));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(132, 206, 235));
        jPanel1.setDoubleBuffered(false);

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        TableSach.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TableSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tác giả ", "Nhà suất bản"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableSach.setRowHeight(40);
        jScrollPane1.setViewportView(TableSach);
        if (TableSach.getColumnModel().getColumnCount() > 0) {
            TableSach.getColumnModel().getColumn(0).setPreferredWidth(100);
            TableSach.getColumnModel().getColumn(1).setPreferredWidth(275);
            TableSach.getColumnModel().getColumn(2).setPreferredWidth(125);
            TableSach.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        btnThongtinSach.setBackground(new java.awt.Color(255, 255, 204));
        btnThongtinSach.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnThongtinSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/account.png"))); // NOI18N
        btnThongtinSach.setText("THÔNG TIN SÁCH");
        btnThongtinSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongtinSachActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Tên Sách :");

        tfTenSach.setBackground(new java.awt.Color(204, 204, 204));
        tfTenSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTenSachKeyReleased(evt);
            }
        });

        cbtheloai.setBackground(new java.awt.Color(204, 204, 204));
        cbtheloai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbtheloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thể loại", " " }));
        cbtheloai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDanhmucItemStateChanged(evt);
            }
        });

        cbDanhmuc.setBackground(new java.awt.Color(204, 204, 204));
        cbDanhmuc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbDanhmuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Danh mục", " " }));
        cbDanhmuc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDanhmucItemStateChanged(evt);
            }
        });

        btnLammoi.setBackground(new java.awt.Color(255, 255, 204));
        btnLammoi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/refresh.png"))); // NOI18N
        btnLammoi.setText("LÀM MỚI");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbDanhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbtheloai, 0, 423, Short.MAX_VALUE))
                            .addComponent(tfTenSach)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnThongtinSach, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbtheloai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDanhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongtinSach, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnThongtinSach.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addTab("          TRA CỨU SÁCH ", new javax.swing.ImageIcon(getClass().getResource("/Imgs/research.png")), jPanel1, ""); // NOI18N

        jTabbedPane2.setBackground(new java.awt.Color(132, 206, 235));

        jPanel3.setBackground(new java.awt.Color(132, 206, 235));
        jPanel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        TableDSmuon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TableDSmuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tác giả", "Nhà suất bản"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TableDSmuon);
        if (TableDSmuon.getColumnModel().getColumnCount() > 0) {
            TableDSmuon.getColumnModel().getColumn(0).setPreferredWidth(50);
            TableDSmuon.getColumnModel().getColumn(1).setPreferredWidth(300);
            TableDSmuon.getColumnModel().getColumn(2).setPreferredWidth(125);
            TableDSmuon.getColumnModel().getColumn(3).setPreferredWidth(150);
        }

        jLabel2.setBackground(new java.awt.Color(0, 51, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Phieumuon.png"))); // NOI18N
        jLabel2.setText("PHIẾU MƯỢN SÁCH :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Lượt mượn :");

        lbluotmuon.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbluotmuon.setText("0");

        lbluotmuon1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbluotmuon1.setText("3");

        btnxoa.setBackground(new java.awt.Color(255, 255, 204));
        btnxoa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/xóa.png"))); // NOI18N
        btnxoa.setText("XÓA");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnguiphieumuon.setBackground(new java.awt.Color(255, 255, 204));
        btnguiphieumuon.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnguiphieumuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/gửi.png"))); // NOI18N
        btnguiphieumuon.setText("GỬI PHIẾU MƯỢN ");
        btnguiphieumuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguiphieumuonActionPerformed(evt);
            }
        });

        cbThoigianmuon.setBackground(new java.awt.Color(255, 255, 204));
        cbThoigianmuon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbThoigianmuon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "14", "21", "28" }));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Songaymuon.png"))); // NOI18N
        jLabel5.setText("Thời gian mượn : ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Ngày");

        lbluotmuon2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbluotmuon2.setText("/ ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbThoigianmuon, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbluotmuon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbluotmuon2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbluotmuon1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnxoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnguiphieumuon, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbluotmuon)
                            .addComponent(lbluotmuon1)
                            .addComponent(lbluotmuon2)
                            .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 338, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguiphieumuon)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbThoigianmuon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jTabbedPane2.addTab("PHIẾU MƯỢN", jPanel3);

        jPanel4.setBackground(new java.awt.Color(132, 206, 235));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Phieumuon.png"))); // NOI18N
        jLabel4.setText("DANH SÁCH CÁC SÁCH ĐANG MƯỢN :");

        TableDangmuon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TableDangmuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Sách", "Ngày mượn", "Ngày trả dự kiến", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TableDangmuon);
        if (TableDangmuon.getColumnModel().getColumnCount() > 0) {
            TableDangmuon.getColumnModel().getColumn(0).setPreferredWidth(300);
            TableDangmuon.getColumnModel().getColumn(1).setPreferredWidth(150);
            TableDangmuon.getColumnModel().getColumn(2).setPreferredWidth(150);
            TableDangmuon.getColumnModel().getColumn(3).setPreferredWidth(150);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("SÁCH ĐANG MƯỢN", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DANH SÁCH MƯỢN", new javax.swing.ImageIcon(getClass().getResource("/Imgs/Danhsachmuon.png")), jPanel2); // NOI18N
        jPanel2.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(ooo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ooo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName(" ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new GUI_DangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnguiphieumuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguiphieumuonActionPerformed
        // TODO add your handling code here:
        if (dangmuon == 0) {
            JOptionPane.showMessageDialog(GUI_DocGia.this, "Danh sách mượn trống!", "Thất bại", JOptionPane.ERROR_MESSAGE);
        } else {
            if (dangmuon > max) {
                if (max == 0) {
                    JOptionPane.showMessageDialog(this, "Bạn đã hết lượt mượn,"
                        + " trả sách đã mượn để được mượn tiếp!", "Thất bại", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Vượt quá số lượng sách được phép mượn! "
                        + "Hãy xóa bớt danh sách mượn", "Thất bại", JOptionPane.ERROR_MESSAGE);
                }
            } else {

                String maPM = "PM" + String.valueOf(CtrPM.CtrDemSoPM());

                Phieumuon phieuMuon = new Phieumuon();
                phieuMuon.setMaPhieumuon(maPM);
                phieuMuon.setMaDocgia(maDocgia);
                phieuMuon.setMaThuthu(null);
                phieuMuon.setSongaymuon(Integer.parseInt(String.valueOf(cbThoigianmuon.getSelectedItem())));
                phieuMuon.setGhichu(null);
                phieuMuon.setTrangthai("Chưa duyệt");

                CtrPM.CtrThemPhieumuon(phieuMuon);

                int rowCount = TableDSmuon.getRowCount();

                for (int i = 0; i < rowCount; i++) {
                    ChitietPhieuMuon ctpm = new ChitietPhieuMuon(maPM, String.valueOf(TableDSmuon.getValueAt(i, 0)),"Chờ duyệt");
                    CtrCTPM.CtrThemCTPhieumuon(ctpm);
                }

                max = max - rowCount;
                //              setGioiHanMuon(gioiHan);
                lbluotmuon1.setText(String.valueOf(max));
                CtrCTPM.CtrSuasoluongmuon(MaTaikhoan, 3 - max);

                JOptionPane.showMessageDialog(this, "Xác nhận thành công!"
                    + "\nMời bạn đến thư viện để nhận sách trong thời gian sớm nhất.");
                DefaultTableModel Model = (DefaultTableModel) TableDSmuon.getModel();
                Model.setRowCount(0);
                setSoluongmuon();
                //              setGioiHanMuon();

                filldatatableDSmuon(maDocgia);

            }
        }
    }//GEN-LAST:event_btnguiphieumuonActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Model = (DefaultTableModel) TableDSmuon.getModel();
        int Row = TableDSmuon.getSelectedRow();
        if (Row == -1) {
            JOptionPane.showMessageDialog(this, " Hãy chọn một cuốn sách ", "", JOptionPane.PLAIN_MESSAGE);
        } else {
            Model.removeRow(Row);
        }
        setSoluongmuon();
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        // TODO add your handling code here:
        filldataTableSach();
    }//GEN-LAST:event_btnLammoiActionPerformed

    private void cbDanhmucItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDanhmucItemStateChanged
        // TODO add your handling code here:
        if (checkLoading) {
            DefaultTableModel Model = (DefaultTableModel) TableSach.getModel();
            String danhmuc = cbDanhmuc.getSelectedItem().toString();
            String theloai = cbtheloai.getSelectedItem().toString();

            if (danhmuc.equalsIgnoreCase("Danh mục") == false
                && theloai.equalsIgnoreCase("Thể loại") == false) {

                Model.setRowCount(0);
                for (Sach sach : CtrSach.CtrgetSachbyBoth(danhmuc, theloai)) {
                    Model.addRow(new Object[]{sach.getMaSach(), sach.getTenSach(), sach.getTacgia(), sach.getNhaXuatBan()});
                }

            } else {
                if (danhmuc.equalsIgnoreCase("Danh mục") == false
                    && theloai.equalsIgnoreCase("Thể loại") == true) {

                    Model.setRowCount(0);
                    for (Sach sach : CtrSach.CtrgetSachbySort(danhmuc, "danhmuc")) {
                        Model.addRow(new Object[]{sach.getMaSach(), sach.getTenSach(), sach.getTacgia(), sach.getNhaXuatBan()});
                    }

                } else {
                    if (danhmuc.equalsIgnoreCase("Danh mục") == true
                        && theloai.equalsIgnoreCase("Thể loại") == false) {

                        Model.setRowCount(0);
                        for (Sach sach : CtrSach.CtrgetSachbySort(theloai, "theloai")) {
                            Model.addRow(new Object[]{sach.getMaSach(), sach.getTenSach(), sach.getTacgia(), sach.getNhaXuatBan()});
                        }

                    } else {
                        filldataTableSach();
                    }
                }
            }
        }
    }//GEN-LAST:event_cbDanhmucItemStateChanged

    private void tfTenSachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTenSachKeyReleased
        // TODO add your handling code here:
        String text = tfTenSach.getText();
        DefaultTableModel Model = (DefaultTableModel) TableSach.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(Model);
        TableSach.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter(text));
    }//GEN-LAST:event_tfTenSachKeyReleased

    private void btnThongtinSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongtinSachActionPerformed
        // TODO add your handling code here:
        int row = TableSach.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Chọn một cuốn sách để xem!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Sach BK = CtrSach.CtrgetIDSach(TableSach.getValueAt(row, 0).toString());
            GUI_Thongtinsach Des = new GUI_Thongtinsach(BK);
            //          DocGia_TTSach_Controller TheController = new DocGia_TTSach_Controller(Des);
            Des.setVisible(true);
            Des.theDocgia = this;
        }
    }//GEN-LAST:event_btnThongtinSachActionPerformed

    Connect ketnoi = new Connect();
    Connection conn = ketnoi.getConnection();

    public boolean KiemtraSLmuon(String masach) {
        DefaultTableModel Model = (DefaultTableModel) TableDSmuon.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(Model);
        sorter.setRowFilter(RowFilter.regexFilter(masach));
        return sorter.getViewRowCount() != 0;
    }

    public void xacnhanmuonsach(Sach sach) {
        DefaultTableModel Model = (DefaultTableModel) TableDSmuon.getModel();
        if (KiemtraSLmuon(sach.getMaSach())) {
            JOptionPane.showMessageDialog(this, "Bạn đã có sách này trong danh mục mượn", "", JOptionPane.PLAIN_MESSAGE);
        } else {
            Model.addRow(new Object[]{sach.getMaSach(), sach.getTenSach(), sach.getTacgia(), sach.getNhaXuatBan()});
            setSoluongmuon();
        }
    }

    public void loadmaTheLoai() {
        cbtheloai.removeAllItems();
        cbtheloai.addItem("Thể loại");
        String sql = "SELECT tentheloai FROM Theloai";
        try {
            Statement statement = conn.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while (rs.next()) {
                this.cbtheloai.addItem(rs.getString(1));
            }
        } catch (SQLException e) {

        }
    }

    public void loadmaDanhMuc() {
        cbDanhmuc.removeAllItems();
        cbDanhmuc.addItem("Danh mục");
        String sql = "SELECT tenDanhmuc FROM Danhmuc";
        try {
            Statement statement = conn.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while (rs.next()) {
                this.cbDanhmuc.addItem(rs.getString(1));
            }
        } catch (SQLException e) {

        }
    }

    public void filldataTableSach() {
        DefaultTableModel Model = (DefaultTableModel) TableSach.getModel();
        Model.setRowCount(0);
        for (Sach BK : CtrSach.CtrgetAllSach()) {
            Object DataRow[] = new Object[4];
            DataRow[0] = BK.getMaSach();
            DataRow[1] = BK.getTenSach();
            DataRow[2] = BK.getTacgia();
            DataRow[3] = BK.getNhaXuatBan();

            Model.addRow(DataRow);
        }
    }

    public void filldatatableDSmuon(String maDocgia) {
        DefaultTableModel Model = (DefaultTableModel) TableDangmuon.getModel();
        Model.setRowCount(0);
        for (ChitietPhieuMuon dsm : CtrCTPM.CtrgetCTPMbymaDocgia(maDocgia)) {
            Model.addRow(new Object[]{dsm.getTenSach(), dsm.getNgaymuon(), dsm.getNgaytradukien(), dsm.getXetduyet()});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_DocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_DocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_DocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_DocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDSmuon;
    private javax.swing.JTable TableDangmuon;
    private javax.swing.JTable TableSach;
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnThongtinSach;
    private javax.swing.JButton btnguiphieumuon;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbDanhmuc;
    private javax.swing.JComboBox<String> cbThoigianmuon;
    private javax.swing.JComboBox<String> cbtheloai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbluotmuon;
    private javax.swing.JLabel lbluotmuon1;
    private javax.swing.JLabel lbluotmuon2;
    private javax.swing.JPanel ooo;
    private javax.swing.JTextField tfTenSach;
    // End of variables declaration//GEN-END:variables
}
