/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controller.ControllerSach;
import Model.Sach;
import javax.swing.JOptionPane;

/**
 *
 * @author UKiel
 */
public class GUI_Thongtinsach extends javax.swing.JFrame {
    Sach BK;
    GUI_DocGia theDocgia ;
    ControllerSach CtrSach;
    
    /**
     * Creates new form 
     */
    public GUI_Thongtinsach(Sach sach) {
        initComponents();
        BK = sach;
        CtrSach = new ControllerSach();
        ThongtinSach(BK);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbtenSach = new javax.swing.JLabel();
        lbTheloai = new javax.swing.JLabel();
        lbDanhmuc = new javax.swing.JLabel();
        lbTacgia = new javax.swing.JLabel();
        lbNhasuatban = new javax.swing.JLabel();
        lbNamsuatban = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbSoluongcon = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpMotaSach = new javax.swing.JTextPane();
        btnThoatCT = new javax.swing.JButton();
        btnThemMuon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(132, 206, 235));

        jPanel1.setBackground(new java.awt.Color(132, 206, 237));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Phieumuon.png"))); // NOI18N
        jLabel1.setText("THÔNG TIN SÁCH");

        lbtenSach.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbtenSach.setForeground(new java.awt.Color(0, 0, 153));
        lbtenSach.setText("TÊN SÁCH ");

        lbTheloai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbTheloai.setForeground(new java.awt.Color(0, 0, 153));
        lbTheloai.setText("THỂ LOẠI ");

        lbDanhmuc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbDanhmuc.setForeground(new java.awt.Color(0, 0, 153));
        lbDanhmuc.setText("DANH MỤC");

        lbTacgia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbTacgia.setForeground(new java.awt.Color(0, 0, 153));
        lbTacgia.setText("TÁC GIẢ");

        lbNhasuatban.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbNhasuatban.setForeground(new java.awt.Color(0, 0, 153));
        lbNhasuatban.setText("NHÀ SUẤT BẢN");

        lbNamsuatban.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbNamsuatban.setForeground(new java.awt.Color(0, 0, 153));
        lbNamsuatban.setText("NĂM SUẤT BẢN");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("MÔ TẢ SÁCH");

        lbSoluongcon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbSoluongcon.setForeground(new java.awt.Color(0, 0, 153));
        lbSoluongcon.setText("SỐ LƯỢNG CÒN");

        tpMotaSach.setBorder(null);
        tpMotaSach.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tpMotaSach.setEnabled(false);
        jScrollPane2.setViewportView(tpMotaSach);

        btnThoatCT.setBackground(new java.awt.Color(255, 255, 204));
        btnThoatCT.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnThoatCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/login.png"))); // NOI18N
        btnThoatCT.setText("Thoát");
        btnThoatCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatCTActionPerformed(evt);
            }
        });

        btnThemMuon.setBackground(new java.awt.Color(255, 255, 204));
        btnThemMuon.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnThemMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/DSPhieumuon.png"))); // NOI18N
        btnThemMuon.setText("Xác nhận mượn");
        btnThemMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMuonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThoatCT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnThemMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbtenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbSoluongcon, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbNamsuatban, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbNhasuatban, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbTacgia, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbTheloai, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbDanhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(43, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbtenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbDanhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbTheloai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbTacgia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbNhasuatban, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbNamsuatban, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbSoluongcon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoatCT, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(479, 479, 479)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(80, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatCTActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatCTActionPerformed

    private void btnThemMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMuonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        theDocgia.xacnhanmuonsach(BK); 
    }//GEN-LAST:event_btnThemMuonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Thongtinsach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Thongtinsach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Thongtinsach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Thongtinsach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
       }
        });
    }
    
    public void ThongtinSach(Sach BK){
        lbtenSach.setText("Tên Sách : " + BK.getTenSach());
        lbDanhmuc.setText("Danh mục : " + CtrSach.CtrmaDanhMuc(BK.getMaDanhMuc()));
        lbTheloai.setText("Thể loại : " + CtrSach.CtrmaTheloai(BK.getMaTheLoai()));
        lbTacgia.setText("Tác giả : " + BK.getTacgia());
        lbNhasuatban.setText("Nhà xuất bản : " + BK.getNhaXuatBan());
        lbNamsuatban.setText("Năm xuất bản : " + BK.getNamXuatBan());
        lbSoluongcon.setText("Số lượng còn : " + BK.getSoluong());
        tpMotaSach.setText(BK.getMota());
        if(BK.getSoluong()<= 0) {
            btnThemMuon.setText("Không có sẵn");
            btnThemMuon.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemMuon;
    private javax.swing.JButton btnThoatCT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDanhmuc;
    private javax.swing.JLabel lbNamsuatban;
    private javax.swing.JLabel lbNhasuatban;
    private javax.swing.JLabel lbSoluongcon;
    private javax.swing.JLabel lbTacgia;
    private javax.swing.JLabel lbTheloai;
    private javax.swing.JLabel lbtenSach;
    private javax.swing.JTextPane tpMotaSach;
    // End of variables declaration//GEN-END:variables
}
